trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.102'

- script: dotnet build --configuration $(buildConfiguration) timey.sln
  displayName: 'dotnet build $(buildConfiguration) timey'
- script: dotnet publish --output $(Build.ArtifactStagingDirectory) timey.sln
  displayName: 'dotnet publish timey'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'
