trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.102'

- script: dotnet build --configuration $(buildConfiguration) timey.sln
  displayName: 'dotnet build $(buildConfiguration) timey'
- script: dotnet publish --output $(Build.ArtifactStagingDirectory) timey.sln
  displayName: 'dotnet publish timey'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish:
    ArtifactName: Drop
    publishLocation: 'Container'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/wwwroot'
    azureSubscription: 'Pay-As-You-Go(0965bb35-0dbf-4993-9dcb-5d75ccd0ca44)'
    Destination: 'AzureBlob'
    storage: 'timeystorageaccount'
    ContainerName: '$web'